version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.1.0
    steps:
      - checkout
      - run:
          name: "npm installing"
          command: "npm install"
      - run:
          name: "npm building"
          command: "npm run build"
  test:
    docker:
      - image: cimg/node:21.1.0
    steps:
    - checkout
    - run:
        name: "npm installing"
        command: "npm install"
    - run:
        name: "npm testing"
        command: "npm test"

  SayHello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "SayHello"
          command: "echo Hello, World!"
workflows:
  build-test-workflow:
    jobs:
      - build
      - SayHello
      - test