export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const CHANGE_SELECTED_AVATARS = "CHANGE_SELECTE_AVATARS";
export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQEST_ROBOTS_FAILED";

export const GET_ALL_ROBOTS = "GET_ALL_ROBOTS";

export const DELETE_ALL_ROBOTS = "DELETE_ALL_ROBOTS";

export const DELETE_ROBOT = "DELETE_ROBOT";

export const CREATE_ROBOT_PAGE = "CREATE_ROBOT_PAGE";

export const ADD_CREATED_ROBOT = "ADD_CREATED_ROBOT";

export const CHANGE_NAME_FIELD = "CHANGE_NAME_FIELD";
export const CHANGE_NICKNAME_FIELD = "CHANGE_NICKNAME_FIELD";
