export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQEST_ROBOTS_FAILED = 'REQEST_ROBOTS_FAILED';

export const CHANGE_NAME_FIELD = 'CHANGE_NAME_FIELD';
export const CHANGE_NICKNAME_FIELD = 'CHANGE_NICKNAME_FIELD';